name = "PkgTest"
uuid = "18c5264b-819f-4f16-8c1e-95793af2f36d"
authors = ["kakinumayuta <kakinuma.y.068@ms.saitama-u.ac.jp> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
